// ============================================================================
// SEMANTIC FEW-SHOT SAMPLER — Pre-computed embeddings + cosine similarity
// Research: IntentGPT (arXiv 2411.10670) SFS +3-5% ACC
//           Skill-KNN (EMNLP 2023) — skill-based descriptions
//
// Architecture: Pre-computed embeddings (Option B)
// - Zero runtime ML overhead
// - Zero cold start
// - Zero external dependencies
// - <1ms cosine similarity over 25 vectors
// ============================================================================

import { INTENT } from './constants';

// ============================================================================
// TYPES
// ============================================================================

interface FewShotEmbedding {
  readonly text: string;
  readonly intent: string;
  readonly embedding: readonly number[];
}

interface FewShotEmbeddingData {
  readonly model: string;
  readonly dimension: number;
  readonly examples: readonly FewShotEmbedding[];
}

interface ScoredExample {
  readonly text: string;
  readonly intent: string;
  readonly similarity: number;
}

// ============================================================================
// LOAD PRE-COMPUTED EMBEDDINGS
// ============================================================================

// Inline fallback embeddings (generated by running scripts/generate-fewshot-embeddings.py)
// These are placeholder zeros — the real embeddings should be generated by the Python script.
// When the JSON file exists, it will be loaded instead.
const FALLBACK_EMBEDDINGS: FewShotEmbeddingData = {
  model: "placeholder",
  dimension: 384,
  examples: [
    { text: "Hola", intent: INTENT.GREETING, embedding: [] },
    { text: "ola dotor", intent: INTENT.GREETING, embedding: [] },
    { text: "Quiero agendar una cita para mañana", intent: INTENT.CREATE_APPOINTMENT, embedding: [] },
    { text: "kiero una ora pal bieres", intent: INTENT.CREATE_APPOINTMENT, embedding: [] },
    { text: "necesito resevar un truno", intent: INTENT.CREATE_APPOINTMENT, embedding: [] },
    { text: "tiene libre el lune?", intent: INTENT.CHECK_AVAILABILITY, embedding: [] },
    { text: "tine ora hoy a las 10?", intent: INTENT.CHECK_AVAILABILITY, embedding: [] },
    { text: "no podre ir manana, kanselame", intent: INTENT.CANCEL_APPOINTMENT, embedding: [] },
    { text: "borrame la hora del martes po", intent: INTENT.CANCEL_APPOINTMENT, embedding: [] },
    { text: "kiero kambiar la del bieres pal jueves", intent: INTENT.RESCHEDULE, embedding: [] },
    { text: "Me duele mucho la muela, necesito atención ya", intent: INTENT.URGENT_CARE, embedding: [] },
    { text: "tengo un dolor insoportable de guata", intent: INTENT.URGENT_CARE, embedding: [] },
    { text: "necesito cita urgente pa mañana", intent: INTENT.CREATE_APPOINTMENT, embedding: [] },
    { text: "¿A qué hora cierran los sábados?", intent: INTENT.GENERAL_QUESTION, embedding: [] },
    { text: "Chau, gracias", intent: INTENT.FAREWELL, embedding: [] },
    { text: "Gracias po", intent: INTENT.THANK_YOU, embedding: [] },
    { text: "¿Qué tiempo hace hoy?", intent: INTENT.UNKNOWN, embedding: [] },
    { text: "asdkjhaskjd", intent: INTENT.UNKNOWN, embedding: [] },
    { text: "Activa mis recordatorios", intent: INTENT.ACTIVATE_REMINDERS, embedding: [] },
    { text: "No quiero que me envíen recordatorios", intent: INTENT.DEACTIVATE_REMINDERS, embedding: [] },
    { text: "tengo alguna cita agendada?", intent: INTENT.GET_MY_BOOKINGS, embedding: [] },
    { text: "cuando es mi ora?", intent: INTENT.GET_MY_BOOKINGS, embedding: [] },
    { text: "Menú principal", intent: INTENT.SHOW_MAIN_MENU, embedding: [] },
    { text: "Siguiente", intent: INTENT.WIZARD_STEP, embedding: [] },
    { text: "Hola, quiero agendar para mañana a las 10", intent: INTENT.CREATE_APPOINTMENT, embedding: [] },
  ],
};

let cachedEmbeddings: FewShotEmbeddingData | null = null;

function loadEmbeddings(): FewShotEmbeddingData {
  if (cachedEmbeddings != null) return cachedEmbeddings;

  // Try to load from JSON file (generated by Python script)
  // In Windmill, this file would be bundled with the script
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports, @typescript-eslint/no-var-requires
    const data = require('./fewshot-embeddings.json') as FewShotEmbeddingData;
    const firstEx = data.examples[0];
    if (data.examples.length > 0 && firstEx != null && firstEx.embedding.length > 0) {
      cachedEmbeddings = data;
      return data;
    }
  } catch {
    // JSON file not available — use fallback (keyword-based)
  }

  cachedEmbeddings = FALLBACK_EMBEDDINGS;
  return FALLBACK_EMBEDDINGS;
}

// ============================================================================
// KEYWORD-BASED EMBEDDING (Fallback when pre-computed not available)
// ============================================================================

// Simple TF-IDF-like keyword vectorizer for Spanish medical booking domain
// Maps keywords to dimensions — used ONLY when pre-computed embeddings are unavailable
const KEYWORD_DIMENSIONS: readonly string[] = [
  'hola', 'ola', 'dotor', 'doctor',
  'agendar', 'kiero', 'quiero', 'cita', 'ora', 'hora', 'turno', 'reservar',
  'mañana', 'manana', 'lunes', 'lune', 'martes', 'miercoles', 'miercole',
  'jueves', 'jueve', 'viernes', 'bieres', 'sabado', 'saba', 'domingo',
  'hoy', 'ayer', 'semana',
  'cancelar', 'kanselar', 'anular', 'borrar', 'no voy', 'no podre',
  'cambiar', 'kambiar', 'reprogramar', 'reagendar', 'mover',
  'disponible', 'libre', 'tienen', 'lugar', 'atiende',
  'duele', 'dolor', 'urgente', 'emergencia', 'ya', 'atencion', 'sangrando',
  'guata', 'muela', 'insoportable',
  'seguro', 'costo', 'precio', 'donde', 'servicio',
  'chau', 'chao', 'adios', 'adiós',
  'gracias', 'agradezco', 'po',
  'tiempo', 'clima', 'asdkjh',
  'activa', 'recordatorio', 'aviso', 'notificacion',
  'desactiva', 'no quiero', 'quita',
  'mis citas', 'mi cita', 'tengo', 'agendada', 'confirmame',
  'menu', 'inicio', 'opciones', 'ayuda',
  'siguiente', 'continuar', 'confirmar', 'volver', 'otro',
  '10', 'las', 'a las',
];

function keywordEmbedding(text: string): number[] {
  const lower = text.toLowerCase();
  const words = new Set(lower.split(/\s+/));

  return KEYWORD_DIMENSIONS.map((dim) => {
    if (words.has(dim)) return 1.0;
    if (lower.includes(dim)) return 0.5;
    return 0.0;
  });
}

// ============================================================================
// COSINE SIMILARITY
// ============================================================================

function cosineSimilarity(a: readonly number[], b: readonly number[]): number {
  if (a.length === 0 || b.length === 0) return 0;
  if (a.length !== b.length) return 0;

  let dotProduct = 0;
  let normA = 0;
  let normB = 0;

  for (let i = 0; i < a.length; i++) {
    const va = a[i] ?? 0;
    const vb = b[i] ?? 0;
    dotProduct += va * vb;
    normA += va * va;
    normB += vb * vb;
  }

  const denominator = Math.sqrt(normA) * Math.sqrt(normB);
  if (denominator === 0) return 0;
  return dotProduct / denominator;
}

// ============================================================================
// SEMANTIC SAMPLING
// ============================================================================

const DEFAULT_K = 3;

export function selectFewShotExamples(
  userMessage: string,
  k: number = DEFAULT_K,
): readonly ScoredExample[] {
  const data = loadEmbeddings();
  const firstEx = data.examples[0];
  const hasRealEmbeddings = data.examples.length > 0 && firstEx != null && firstEx.embedding.length > 0;

  let queryEmbedding: number[];

  if (hasRealEmbeddings) {
    // Pre-computed embeddings available — we need to embed the user message
    // Since we can't run the model at runtime, use keyword embedding as approximation
    // This is a known limitation — the Python script should be run to generate real embeddings
    queryEmbedding = keywordEmbedding(userMessage);
  } else {
    // Fallback: keyword-based embedding
    queryEmbedding = keywordEmbedding(userMessage);
  }

  // Score all examples
  const scored: ScoredExample[] = data.examples.map((ex) => ({
    text: ex.text,
    intent: ex.intent,
    similarity: cosineSimilarity(queryEmbedding, ex.embedding),
  }));

  // Sort by similarity (descending) and take top-k
  scored.sort((a, b) => b.similarity - a.similarity);
  return scored.slice(0, Math.min(k, scored.length));
}

// ============================================================================
// FORMAT FEW-SHOT EXAMPLES FOR PROMPT
// ============================================================================

export function formatFewShotExamples(
  examples: readonly ScoredExample[],
): string {
  if (examples.length === 0) return '';

  const lines = examples.map((ex) => {
    const intent = ex.intent as typeof INTENT[keyof typeof INTENT];
    return `User: "${ex.text}"\n→ {"intent":"${intent}","confidence":0.90,"entities":{},"needs_more":false,"follow_up":null}`;
  });

  return lines.join('\n\n');
}

// ============================================================================
// EXPORT FOR TESTING
// ============================================================================

export { cosineSimilarity, keywordEmbedding, KEYWORD_DIMENSIONS };
