[mypy]
strict_equality = True
strict = True
warn_return_any = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
no_implicit_optional = True
warn_redundant_casts = False
warn_unused_ignores = False
show_error_codes = True
disallow_any_generics = False
disallow_any_unimported = False
disallow_any_expr = False

[mypy-wmill.*]
ignore_missing_imports = True

[mypy-asyncpg]
ignore_missing_imports = True

[pydantic-mypy]
init_typed = true
init_forbid_extra = true
warn_required_dynamic_aliases = true
