from typing import Any, Dict, Optional, Union

def get_variable(path: str) -> str: ...
def set_variable(path: str, value: Any) -> None: ...
def get_resource(path: str) -> Dict[str, Any]: ...
def set_resource(path: str, body: Dict[str, Any]) -> None: ...
def run_script_by_path(path: str, args: Dict[str, Any]) -> Any: ...
def run_script_by_path_async(path: str, args: Dict[str, Any]) -> str: ...
def get_result(job_id: str) -> Any: ...
def get_state() -> Optional[Any]: ...
def set_state(state: Any) -> None: ...
def set_progress(progress: float) -> None: ...
def cancel_running() -> None: ...
