from __future__ import annotations

def get_variable(path: str) -> str: ...
def set_variable(path: str, value: object) -> None: ...
def get_resource(path: str) -> dict[str, object]: ...
def set_resource(path: str, body: dict[str, object]) -> None: ...
def run_script_by_path(path: str, args: dict[str, object]) -> object: ...
def run_script_by_path_async(path: str, args: dict[str, object]) -> str: ...
def get_result(job_id: str) -> object: ...
def get_state() -> object | None: ...
def set_state(state: object) -> None: ...
def set_progress(progress: float) -> None: ...
def cancel_running() -> None: ...
def get_job_status(job_id: str) -> str: ...
