from __future__ import annotations

class Connection:
    async def fetch(self, query: str, *args: object) -> list[dict[str, object]]: ...
    async def fetchrow(self, query: str, *args: object) -> dict[str, object] | None: ...
    async def fetchval(self, query: str, *args: object) -> object: ...
    async def execute(self, query: str, *args: object) -> str: ...
    async def close(self) -> None: ...

async def connect(dsn: str) -> Connection: ...
