from __future__ import annotations

from typing import Any

class Record:
    def __getitem__(self, key: str) -> object: ...
    def get(self, key: str, default: object = None) -> object: ...
    def keys(self) -> list[str]: ...

class Connection:
    async def fetch(self, query: str, *args: object) -> list[dict[str, object]]: ...
    async def fetchrow(self, query: str, *args: object) -> dict[str, object] | None: ...
    async def fetchval(self, query: str, *args: object) -> object: ...
    async def execute(self, query: str, *args: object) -> str: ...
    async def close(self) -> None: ...

class Pool:
    async def acquire(self) -> Connection: ...
    async def release(self, conn: Connection) -> None: ...
    async def close(self) -> None: ...
    async def fetch(self, query: str, *args: object) -> list[dict[str, object]]: ...
    async def fetchrow(self, query: str, *args: object) -> dict[str, object] | None: ...
    async def execute(self, query: str, *args: object) -> str: ...

async def connect(dsn: str, **kwargs: Any) -> Connection: ...
async def create_pool(dsn: str, **kwargs: Any) -> Pool: ...
